<?php

/* DO NOT EDIT THIS FILE! Use config.php for overriding stuff from here */

define('STATUS_NEW', 0);
define('STATUS_OK', 1);
define('STATUS_GROUP_NOT_AVAILABLE', 2);
define('STATUS_GROUP_ACCESS_DENIED', 4);
define('STATUS_GROUP_UNKNOWN', 6);
define('STATUS_POST_FAILED', 8);

$config = array(
  'dbhost' => '',
  'dbport' => '',
  'dbname' => '',
  'dbuser' => '',
  'dbpasswd' => '',

  'tasks_table' => 'tasks',
  'tasks_limit' => 1,

  'apps_json' => '../apps.json',
);

$options = array(
  'vk_post' =>  array(
    'from_group' => 1,
    'signed' => 0,
    'friends_only' => 0,
    'expires_in' => 0,
    'attachments' => '',
  ),
  'curl_options' => array(
    CURLOPT_POST            => true,
    CURLOPT_RETURNTRANSFER  => true,
    CURLOPT_HEADER          => false,
    CURLOPT_SSL_VERIFYPEER  => true,
    CURLOPT_SSL_VERIFYHOST  => 2,
    CURLOPT_ENCODING        => "",
    CURLOPT_USERAGENT       => "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:21.0) Gecko/20100101 Firefox/21.0",
    //CURLOPT_IPRESOLVE       => CURL_IPRESOLVE_V4,
  ),
);
